version: '3.8'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  redis-node-0:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: 'colovu/redis-cluster:5.0'
    environment:
      - 'REDIS_PASSWORD=colovu'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'


  redis-cluster-init:
    image: 'colovu/redis-cluster:5.0'
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDISCLI_AUTH=colovu'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_CLUSTER_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'


# 定义本地数据卷，由系统管理，需要手动删除
volumes:
  redis_data:
    driver: local
